
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/egresados_db
      SPRING_DATASOURCE_USERNAME: egresados_db_owner
      SPRING_DATASOURCE_PASSWORD: npg_n7xtLuBcRMZ5
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: egresados_db
      POSTGRES_USER: egresados_db_owner
      POSTGRES_PASSWORD: npg_n7xtLuBcRMZ5
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
